name: custompaintapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  cupertino_icons: ^1.0.2
  flutter_colorpicker: ^1.1.0
  flutter_svg: ^2.0.9
  file_saver: ^0.2.9
  font_awesome_flutter: ^10.6.0
  url_launcher: ^6.2.1
  universal_html: ^2.2.4
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  universal_platform: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/svgs/
